name: advanced-ci

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running tests"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - run: echo "Building application for main"

  pr-check:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'

    steps:
      - run: echo "Running pull request checks"
